[workspace]

members = ["modoh-bin", "modoh-lib"]
exclude = ["submodules/hyper-tls"]
resolver = "2"

[profile.release]
codegen-units = 1
incremental = false
lto = "fat"
opt-level = 3
panic = "abort"
strip = true
