## Configuration file for the (M)ODoH proxy
## We should note that this proxy is always used with TLS termination reverse proxy in front of it.
## This proxy is not designed to be exposed to the internet directly.

## Listen address [default: "0.0.0.0"]
listen_address = "0.0.0.0"

## Listen port [default: 8080]
listen_port = 8080

## Serving hostname [default: "localhost"]
## This will be used to check host header of incoming requests.
hostname = "modoh.example.com"

## Serving path [default: "/proxy"]
path = "/proxy"

## Maximum number of subsequent nodes (relays and target resolver) [default: 3]
max_subsequent_nodes = 3

## (Optional, but highly reccomended to set)
## Authentication of source, typically user clients, using Id token
[auth]

## Token validation method, multiple methods can be configured
[[auth.token]]
## Token issuer
token_issuer_url = "https://example.com/auth"

## Allowed client Ids
client_ids = ["client_id_1", "client_id_2"]

## (Optional, but highly reccomended to set)
## Access control of source, typically relays, using source ip address and nexthop destination domain
[access]
## Allowed source ip addrs
## (TODO: from dns, should we fetch addrs associated with a given list of authorized relay domains? but such addresses may be compromised)
## This is evaluated when no authorization header is given in the request or no token validation is configured.
## This happens typcially for forwarded requests from a relay, not a client.
allowed_source_ip_addresses = ["192.168.1.1", "192.168.1.2"]

## Allowed destination target and relay domains
allowed_destination_domains = ["example.com", "example.net"]
