[package]
name = "modoh-server"
description = "Relay and target for (Mutualized) Oblivious DNS over HTTPS with Authorization"
version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
categories.workspace = true
keywords.workspace = true
edition.workspace = true
publish.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["otel-full", "otel-evil-trace", "qrlog"]
otel-full = ["otel-trace", "otel-metrics", "otel-instance-id"]
otel-trace = [
  "opentelemetry/trace",
  "opentelemetry_sdk/trace",
  "opentelemetry-stdout/trace",
  "opentelemetry-otlp/trace",
  "dep:tracing-opentelemetry",
  "otel-base",
]
otel-metrics = [
  "modoh-server-lib/metrics",
  "opentelemetry/metrics",
  "opentelemetry_sdk/metrics",
  "opentelemetry-stdout/metrics",
  "opentelemetry-otlp/metrics",
  "otel-base",
]
otel-base = [
  "opentelemetry_sdk/rt-tokio",
  "dep:opentelemetry-semantic-conventions",
]
otel-instance-id = ["dep:uuid"]
qrlog = [
  "modoh-server-lib/qrlog",
  "tracing-subscriber/json",
  "tracing-subscriber/chrono",
]

# DO NOT USE THIS IN PRODUCTION
otel-evil-trace = ["modoh-server-lib/evil-trace", "otel-trace"]

[dependencies]
modoh-server-lib = { path = "../modoh-lib", default-features = false, features = [
  "rustls",
] }

anyhow = "1.0.100"
mimalloc = { version = "*", default-features = false }
serde = { version = "1.0.228", default-features = false, features = ["derive"] }
derive_builder = "0.20.2"
tokio = { version = "1.48.0", default-features = false, features = [
  "net",
  "rt-multi-thread",
  "time",
  "sync",
  "macros",
] }
async-trait = "0.1.89"
url = "2.5.7"

# config
clap = { version = "4.5.51", features = ["std", "cargo", "wrap_help"] }
toml = { version = "0.9.8", default-features = false, features = [
  "parse",
  "serde",
] }
hot_reload = "0.2.0"

# tracing and metrics
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.20", features = ["fmt"] }
tracing-opentelemetry = { version = "0.31.0", optional = true }
opentelemetry = { version = "0.30.0", optional = true }
opentelemetry_sdk = { version = "0.30.0", features = [
  "rt-tokio",
  "spec_unstable_metrics_views",
], optional = true }
opentelemetry-stdout = { version = "0.30.0", optional = true }
opentelemetry-otlp = { version = "0.30.0", optional = true, features = [
  "grpc-tonic",
] }
opentelemetry-semantic-conventions = { version = "0.30.0", optional = true, features = [
  "semconv_experimental",
] }

# add random otel service id whenever restarting
uuid = { version = "1.18.1", default-features = false, features = [
  "v4",
  "fast-rng",
], optional = true }

# ip address
ipnet = { version = "2.11.0" }
