services:
  modoh-server:
    image: jqtype/modoh-server:latest # ghcr.io/junkurihara/modoh-server:latest also works
    container_name: modoh-server
    init: true
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:8080/tcp
    build: # Uncomment if you build yourself
      context: ../
      dockerfile: ./docker/Dockerfile # based on ubuntu 22.04 and build x86_64-unknown-linux-gnu
      # platforms: # Choose your platforms
      # - "linux/amd64"
      # - "linux/arm64"
    environment:
      - LOG_LEVEL=debug
      - LOG_TO_FILE=true
      - HOST_USER=jun
      - HOST_UID=501
      - HOST_GID=501
      # - WATCH=true
      # - DISABLE_OTEL=true # opentelemetry is disabled if DISABLE_OTEL=true (default: false)
      - OTLP_ENDPOINT=http://otel-collector:4317 # opentelemetry endpoint (default: http://localhost:4317)
      # - ENABLE_QRLOG=true # qrlog is enabled if ENABLE_QRLOG is set. Record in `/modoh/log/qrlog.log` [default=false]
    tty: false
    privileged: true
    volumes:
      - ./log:/modoh/log:rw
      - ../.private/cdn_ips.txt:/etc/cdn_ips.txt:ro
      - ../.private/modoh-server.toml:/etc/modoh-server.toml:ro
      # NOTE: To correctly enable "watch" in docker,
      # ** you should mount not a file but a dir mapped to /modoh/config including "modoh-server.toml" due to the limitation of docker **
      # e.g, - ./modoh-config:/modoh/config
    networks:
      - net-otel # When you use opentelemetry collector

networks:
  # opentelemetry collector network should be created beforehand
  net-otel:
    external: true
