services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: unless-stopped
    ports:
      - 127.0.0.1:4317:4317 # gRPC
      - 127.0.0.1:13133:13133 # health check
      - 127.0.0.1:1777:1777 # pprof
      - 127.0.0.1:55679:55679 # zpages
    expose:
      - 4317 # OTLP gRPC
      - 8889 # Prometheus exporter metrics
      - 8888 # Prometheus metrics exposed by the collector
    volumes:
      - ./otel-config.yml:/etc/otel-config.yml
      - /var/run/docker.sock:/var/run/docker.sock # docker env detector
    command: ["--config=/etc/otel-config.yml"]
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    # healthcheck:
    #   test: ["CMD-SHELL", "wget -nv -t1 otel-collector:13133 || exit 1"]
    networks:
      - net-otel

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    restart: unless-stopped
    ports:
      - 127.0.0.1:16686:16686 # frontend
    expose:
      - 4317 # OTLP
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - net-otel

  # Prometheus Remote Write Endpoint
  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    expose:
      - 9009
    command: ["--config.file=/etc/mimir.yml"]
    volumes:
      - ./otel-data/mimir:/var/mimir:rw
      - ./mimir.yml:/etc/mimir.yml
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - net-otel

  # Visualize metrics
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 127.0.0.1:3000:3000 # frontend
    volumes:
      - ./otel-data/grafana:/var/lib/grafana
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - net-otel

  # prometheus:
  #   image: prom/prometheus:latest
  #   container_name: prometheus
  #   command: ["--config.file=/etc/prometheus/prometheus.yml"]
  #   volumes:
  #     # - ./data/prometheus:/prometheus
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "127.0.0.1:9090:9090" # frontend
  #   networks:
  #     - net-otel

networks:
  net-otel:
    name: net-otel
    driver: bridge
