receivers:
  otlp: # the OTLP receiver the app is sending traces to
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317" # for docker
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
      paging:
      processes:
      process:

processors:
  batch:
  resourcedetection/docker:
    detectors: [env, docker]
    timeout: 2s
    override: false

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 2 # default
    sampling_thereafter: 500 # default
  otlp/jaeger: # Jaeger supports OTLP directly
    endpoint: http://jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"

extensions:
  zpages: # https://github.com/open-telemetry/opentelemetry-collector/blob/main/extension/zpagesextension
    endpoint: 0.0.0.0:55679 # for docker
  pprof: # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/pprofextension
    endpoint: 0.0.0.0:1777 # for docker
  health_check: # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/healthcheckextension
    endpoint: 0.0.0.0:13133 # for docker


service:
  pipelines:
    traces/dev:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlp/jaeger]
    metrics/prod:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
    metrics/host:
      receivers: [hostmetrics]
      processors: [resourcedetection/docker, batch]
      exporters: [debug, prometheus]

  extensions: [zpages, pprof, health_check]
