[package]
name = "modoh-server-lib"
version = "0.1.0"
description = "Relay and target libraly for (Mutualized) Oblivious DNS over HTTPS with Authorization"
authors = ["Jun Kurihara"]
homepage = "https://github.com/junkurihara/modoh-server"
repository = "https://github.com/junkurihara/modoh-server"
license = "MIT"
readme = "../README.md"
categories = [
  "asynchronous",
  "network-programming",
  "command-line-utilities",
  "web-programming::http-server",
]
keywords = [
  "dns",
  "https",
  "dns-over-https",
  "doh",
  "oblivious-dns-over-https",
  "odoh",
  "mutualized-oblivious-dns",
  "mutualized-odoh",
  "modoh",
  "relay",
  "authorization",
]
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["native-tls"]
native-tls = ["hyper-tls"]
metrics = []
rustls = []

[dependencies]
futures = { version = "0.3.29", default-features = false, features = [
  "std",
  "async-await",
] }
tokio = { version = "1.35.0", features = [
  "net",
  "rt-multi-thread",
  "time",
  "sync",
  "macros",
] }
anyhow = "1.0.75"
tracing = "0.1.40"
thiserror = "1.0.51"
async-trait = "0.1.74"

# http handling for both client and server
url = "2.5.0"
rustc-hash = "1.1.0"
hyper = { version = "1.1.0", default-features = false }
http = "1.0.0"
http-body-util = "0.1.0"
hyper-util = { git = "https://github.com/junkurihara/hyper-util", features = [
  "full",
], rev = "85a92f3da3c1b8b0d20c71f8d9a7063f98ab4eb9" }

# http handling for client
hyper-tls = { git = "https://github.com/junkurihara/hyper-tls", features = [
  "alpn",
  "vendored",
], rev = "c4e94dd3a5d2b97ad3c972d3bdc8e4f8b9925e72", optional = true }
# hyper-rustls = { version = "0.24.2", default-features = false, features = [
#   "tokio-runtime",
#   "webpki-tokio",
#   "http1",
#   "http2",
# ] }

# modoh target handling
odoh-rs = { git = "https://github.com/junkurihara/odoh-rs" }
rand = "0.8.5"
base64 = "0.21.5"
byteorder = "1.5.0"

# validation of id token
serde = { version = "1.0.193", default-features = false }
auth-validator = { git = "https://github.com/junkurihara/rust-token-server", package = "rust-token-server-validator", branch = "develop" }
serde_json = { version = "1.0.108" }

# access control
ipnet = { version = "2.9.0" }
cedarwood = { version = "0.4.6" }
regex = { version = "1.10.2" }
