name: Nightly and release build

on:
  push:
    branches:
      - "develop"
  pull_request:
    types: [closed]
    branches:
      - main

env:
  #   GHCR: ghcr.io
  #   GHCR_IMAGE_NAME: ${{ github.repository }}
  DH_REGISTRY_NAME: jqtype/modoh-server

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }} || ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
    strategy:
      fail-fast: false

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DH_REGISTRY_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Release Build and push x86_64
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref == 'develop' && github.event.pull_request.base.ref == 'main' && github.event.pull_request.merged == true }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DH_REGISTRY_NAME }}:latest
          file: ./docker/Dockerfile
          cache-from: type=gha,scope=doh-auth-proxy-latest
          cache-to: type=gha,mode=max,scope=doh-auth-proxy-latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: Nightly build and push x86_64
        if: ${{ (github.ref_name == 'develop') && (github.event_name == 'push') }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DH_REGISTRY_NAME }}:nightly
          file: ./docker/Dockerfile
          cache-from: type=gha,scope=doh-auth-proxy-nightly
          cache-to: type=gha,mode=max,scope=doh-auth-proxy-nightly
          labels: ${{ steps.meta.outputs.labels }}
